

# Application

spring.application.name=quantity-measurement
server.port=8080

# MySQL Database

spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=Asquare#27
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional (format SQL)

spring.jpa.properties.hibernate.format_sql=true

# =========================

# OAuth2 - GitHub Config

# =========================

spring.security.oauth2.client.registration.github.client-id=Ov23liLixuGrqBHlazPX
spring.security.oauth2.client.registration.github.client-secret=820af730d7107f64bc0f8cc2c66f6c133442facb
spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=id
